apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ms-ticket
  name: ms-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-ticket
  template:
    metadata:
      labels:
        app: ms-ticket
    spec:
      containers:
      - image: pomeo44/ms-ticket:38
        imagePullPolicy: Always
        name: ms-ticket
        ports:
        - containerPort: 8080
