apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application }}
  labels:
    app: {{ .Values.application }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application }}
  template:
    metadata:
      labels:
        app: {{ .Values.application }}
    spec:
      containers:
        - name: {{ .Values.application }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port.http }}
              protocol: TCP
            - name: debug
              containerPort: {{ .Values.container.port.debug }}
              protocol: TCP
          envFrom:
          - prefix: ""
            configMapRef:
              name: {{ .Values.application }}