apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application }}
  labels:
    app: {{ .Values.application }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application }}
  template:
    metadata:
      labels:
        app: {{ .Values.application }}
    spec:
      containers:
        - name: {{ .Values.application }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port.http }}
              protocol: TCP
            - name: debug
              containerPort: {{ .Values.container.port.debug }}
              protocol: TCP
          env:
            - name: "JAVA_OPTS"
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            {{ - toYaml .Values.container.env | nindent 12 }}
          envFrom:
          - prefix: ""
            configMapRef:
              name: {{ .Values.application }}