apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application }}
  labels:
    app: {{ .Values.application }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.http }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.port.debug }}
      protocol: TCP
      name: debug
  selector:
    app: {{ .Values.application }}
