spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/route}?currentSchema=route
    username: ${DATASOURCE_USER:route_ms}
    password: ${DATASOURCE_PASSWORD:route_ms}
  liquibase:
    enabled: true
    parameters:
      schema: route
      text_array_type: ARRAY
    change-log: db/changelog-master.xml
  jpa:
    hibernate.ddl-auto: none
    show-sql: false

logging:
  level:
    ROOT: info
    com.flixbus.route: debug
    org.apache.coyote.http11: info