spring:
  h2.console.enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:testdb;\
              INIT=CREATE SCHEMA IF NOT EXISTS ROUTE\\;SET SCHEMA ROUTE;"
    username: sa
    password:
  cloud:
    kubernetes:
      enabled: false