application: route
replicaCount: 2
image:
  repository: "pomeo44/ms-ticket"
  tag: "1.0"
  pullPolicy: IfNotPresent
container:
  port:
    http: 8080
    debug: 5005
service:
  type: ClusterIP
  port:
    http: 8080
    debug: 5005
